services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USERPOLLING=true
      - WDS_SOCKET_PORT=0
    command: npm start
    depends_on:
      - backend
  
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - backend
      - test-db
    env_file:
      - ./backend/tests/.env.test
    restart: "no"

  test-db:
    image: postgres:13
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    env_file:
      - ./backend/tests/.env.test
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  postgres_test_data: