services:
  db:
    image: postgres:13
    volumes:
      - speechtrap_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --workers 4
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USERPOLLING=true
      - WDS_SOCKET_PORT=0
    command: npm run build
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      app-network:
        aliases:
          - nginx

networks:
  app-network:
    driver: bridge

volumes:
  speechtrap_postgres_data:
  postgres_test_data: