name: Backend Tests

on:
  push:
    branches: [ develop ]
  
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      test-db:
        image: postgres:latest
        env:
          POSTGRES_DB: speechtrap_test
          POSTGRES_USER: speechtrap
          POSTGRES_PASSWORD: speechtrap
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U speechtrap -d speechtrap_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      
      - name: Check PostgreSQL service logs
        run: |
          docker ps -a
          docker logs $(docker ps -a -q --filter "ancestor=postgres:latest" --latest)
      
      - name: Wait for PostgreSQL and test connection
        run: |
          for i in {1..30}; do
            echo "Attempt $i/30: Checking localhost:5432..."
            if pg_isready -h localhost -p 5432 -U speechtrap -d speechtrap_test; then
              echo "Database is ready!"
              psql -h localhost -p 5432 -U speechtrap -d speechtrap_test -c "SELECT 1;" && echo "Connection successful!"
              break
            else
              echo "Database not ready yet."
              pg_isready -h localhost -p 5432 -U speechtrap -d speechtrap_test || echo "pg_isready failed"
              psql -h localhost -p 5432 -U speechtrap -d speechtrap_test -c "SELECT 1;" || echo "psql failed with: $?"
            fi
            sleep 2
          done
      
      - name: Run tests
        working-directory: ./backend
        env:
          POSTGRES_DB: speechtrap_test
          POSTGRES_USER: speechtrap
          POSTGRES_PASSWORD: speechtrap
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pytest -v --cov=app --cov-report=term-missing